let car = 'subaru';

console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru'); // True

console.log("Is car == 'honda'? I predict False.");
console.log(car == 'honda'); // False

console.log("Is car != 'toyota'? I predict True.");
console.log(car != 'toyota'); // True

console.log("Is car != 'subaru'? I predict False.");
console.log(car != 'subaru'); // False

console.log("Is car === 'subaru'? I predict True.");
console.log(car === 'subaru'); // True

console.log("Is car === 'Subaru'? I predict False.");
console.log(car === 'Subaru'); // False

console.log("Is car !== 'honda'? I predict True.");
console.log(car !== 'honda'); // True

console.log("Is car !== 'subaru'? I predict False.");
console.log(car !== 'subaru'); // False

console.log("Is car.startsWith('su')? I predict True.");
console.log(car.startsWith('su')); // True

console.log("Is car.endsWith('ru')? I predict True.");
console.log(car.endsWith('ru')); // True
