let alien_color: string = 'green';

if (alien_color === 'green') {
    console.log("You just earned 5 points!");
} else if (alien_color === 'yellow') {
    console.log("You just earned 10 points!");
} else if (alien_color === 'red') {
    console.log("You just earned 15 points!");
} else {
    console.log("Unknown alien color!");
}


let alien_color: string = 'yellow';

if (alien_color === 'green') {
    console.log("You just earned 5 points!");
} else if (alien_color === 'yellow') {
    console.log("You just earned 10 points!");
} else if (alien_color === 'red') {
    console.log("You just earned 15 points!");
} else {
    console.log("Unknown alien color!");
}


let alien_color: string = 'red';

if (alien_color === 'green') {
    console.log("You just earned 5 points!");
} else if (alien_color === 'yellow') {
    console.log("You just earned 10 points!");
} else if (alien_color === 'red') {
    console.log("You just earned 15 points!");
} else {
    console.log("Unknown alien color!");
}
