let favorite_fruits: string[] = ["Banana", "Apple", "Mango"];

if (favorite_fruits.includes("Banana")) {
    console.log("You really like bananas!");
}

if (favorite_fruits.includes("Apple")) {
    console.log("You really like apples!");
}

if (favorite_fruits.includes("Mango")) {
    console.log("You really like mangoes!");
}

if (favorite_fruits.includes("Orange")) {
    console.log("You really like oranges!");
}

if (favorite_fruits.includes("Grapes")) {
    console.log("You really like grapes!");
}
